### ISSUE TITLE
0.4.0 RELEASE TODO LIST

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#243]
__TENTATIVE RELEASE DATE: December 20, 2015__

In this issue, I will gather tasks that need to be done before (or on the day of) the release of 0.4.0):
- [x] Update SuperTux credits
 - [x] Include Jacob "maths22" Burroughs ("packaging, nightly builds"), Karkus (development, SuperTux editor, other things) and Hume (development, level editing)
 - [x] Update list of translators in credits
 - [x] Add people we might have forgotten during previous rounds (if there are any)
 - [x] Integrate changes to submodules (xref SuperTux/tinygettext#1, SuperTux/squirrel#1)

- [x] Update localization files from Transifex
- [x] Add "Thank you" announcement stating that localizers can take it easy now (apologize for string changes after string freeze)
- [x] Update add-ons that need updating (including those with changed strings which were updated in the source files.
 - [x] Create language add-ons for all supported languages. 

- [x] Run through Coverity to make sure that intermittent changes didn't break the build
- [x] Update readme.md to reflect recent changes (still talks about abandoning the forest world etc.)
- [x] Create release notes, update `NEWS.md` for 0.4.0
- [x] *git tag* the release as 0.4.0, create a new branch containing 0.4.0 code, main development will continue on the master branch.
- [x] Compile packages for major operating systems (Linux, Windows, Mac OS X) (@maths22)
- [x] Create release announcement covering most important commits since 0.3.5a (also include release notes).

- [x] PR / Social Media coverage, including:
 - [x] Twitter (@supertux_team)
 - [x] FreeGameDev.org
 - [x] Mailing list

- [x] Notify people depending on the release about it. This includes:
 - [x] Homebrew Games https://github.com/Homebrew/homebrew-games
 - [x] Android port https://github.com/pelya/commandergenius
 - [x] Arch Linux: https://www.archlinux.org/packages/community/x86_64/supertux/ (Flag out of date when released, CC: @svenstaro)
 - [x] Debian (CC: @Vincent-C)
 - [x] Fedora (CC: @amigadave)
 - [x] PortableApps.com guys in order to create a new version of Portable SuperTux
 - [x] Softonic.com http://supertux.softonic.com/

**Edit by @maxteufel, 2015-12-03 16:15 UTC:** Added Arch Linux to list of people to notify
**Edit by @maxteufel, 2015-12-03 16:25 UTC:** Added Debian and Fedora to list of people to notify
**Edit by @maxteufel, 2015-12-18 19:29 UTC:** `NEWS.md` should be updated **before** tagging *0.4.0*

**Comment by giby** [comment]
I think I updated the translators when they were active enough...

**Comment by Karkus476** [comment]
I don't mind to being added to the credits :)

**Comment by tobbi** [comment]
Okay, I guess I will credit you as "Karkus476" and for the above-mentioned things, right?

**Comment by Karkus476** [comment]
@tobbi I suppose just 'Programming'

**Comment by maxteufel** [comment]
Package maintainers, CC: @svenstaro, @Vincent-C, @amigadave 

Since GitHub apparently doesn't send out emails when mentioning someone in an edit.

**Comment by svenstaro** [comment]
Uhm what do you need me to do at this point?

**Comment by maxteufel** [comment]
Just make sure to keep an eye on the repo around 2015-12-20 ;)

**Comment by svenstaro** [comment]
Just flag my package out of date and I'll get noticed.

**Comment by Karkus476** [comment]
@tobbi We aren't abandoning the Forest World, it isn't in the "Story Mode", so it isn't considered official. There is a lot of work to do on it.

**Comment by maxteufel** [comment]
Draft release notes + announcement: <https://gist.github.com/maxteufel/d4a12ba9dabfcd0a3bc0>

**Comment by marc280492** [comment]
@tobbi Please, read my comment in your message: https://www.transifex.com/arctic-games/supertux/announcements/4994/

Also you can please change my name in credits from Prisma Traduccions to Marc Celeiro (with the nickname maceleiro)?

Thanks and sorry :(

**Comment by tobbi** [comment]
I'm on it!

**Comment by marc280492** [comment]
@tobbi Thanks! :+1:

**Comment by maxteufel** [comment]
> The comment on Transifex:
> Really, I'm sorry too but I have seen it now.

You don't have to be sorry, the great thing is that translations are now handled as add-ons, meaning that they can be updated without having to release a new version.

**Comment by marc280492** [comment]
@maxteufel This is fantastic!! Great job!!

PS: The Christmas theme is so cool!

**Comment by tobbi** [comment]
@marc280492 Updated credits and l10n files. Thanks! I, for once, am glad when this release is over!

**Comment by marc280492** [comment]
@tobbi @maxteufel And please, don't forget to update the version in Softonic (http://supertux.softonic.com/). Many people download the program from there :)

**Comment by tobbi** [comment]
Added to the list.

**Comment by Karkus476** [comment]
@tobbi Actually, that's quite important. We don't want someone to upload a virus which gets downloaded under the name "SuperTux"

**Comment by tobbi** [comment]
forum post: http://forum.freegamedev.net/viewtopic.php?f=67&t=6696

**Comment by tobbi** [comment]
Deferring add-on update for now (can be done whenever; not blocking release)

**Comment by tobbi** [comment]
Twitter: https://twitter.com/supertux_team/status/678605587240775680

**Comment by tobbi** [comment]
Portable Apps: http://portableapps.com/development/outdated#comment-225770

**Comment by marc280492** [comment]
Hey Tobbi, I'll update Wikipedia pages related to SuperTux. Can I use the oficial release notes, SuperTux logo and I can take a screenshot of the game to put it? Thanks!

**Comment by tobbi** [comment]
Mailing list post: http://lists.lethargik.org/pipermail/supertux-devel-lethargik.org/2015-December/000047.html

@marc280492 I think you can.

**Comment by marc280492** [comment]
@tobbi Please add in to-do list: update the version in uptodow http://supertux.uptodown.com/ :)

**Comment by tobbi** [comment]
@marc280492 Added!

**Comment by svenstaro** [comment]
The release on Github is broken as it doesn't include submodules apparently:

    -- Found PhysFS: /usr/lib/libphysfs.so  
    -- Found CURL: /usr/lib/libcurl.so (found version "7.46.0") 
    CMake Error at CMakeLists.txt:200 (MESSAGE):
      Cound not find GIT or valid version.cmake.  Version information will be
      invalid.
    
    
    CMake Error at CMakeLists.txt:202 (INCLUDE):
      include could not find load file:
    
        /build/supertux/src/supertux-0.4.0/version.cmake

**Comment by tobbi** [comment]
Did you use this? https://github.com/SuperTux/supertux/releases/download/v0.4.0/supertux-0.4.0.tar.bz2

**Comment by svenstaro** [comment]
No, I used https://github.com/SuperTux/supertux/archive/v0.4.0.tar.gz. The other link seems to work better. Strange, I was under the impression that automatic Github also included all the submodules.

**Comment by tobbi** [comment]
Apparently, they don't, and since the .git directory is not included, you can't even update the submodules.

**Comment by tobbi** [comment]
Notified computerbild.de using their web form.

**Comment by tobbi** [comment]
Arch updated: https://twitter.com/ArchUpdates/status/678975746283450368 https://twitter.com/ArchUpdates/status/678975743410356224

**Comment by Vincent-C** [comment]
[Uploaded to Debian](https://lists.debian.org/debian-devel-changes/2015/12/msg03123.html). Congrats on releasing 0.4.0!

**Comment by maxteufel** [comment]
Fedora updated their packages in Rawhide. https://apps.fedoraproject.org/packages/supertux/builds/

**Comment by Karkus476** [comment]
I've uploaded the Windows version to Softonic (under the name Karkus476) it's currently being verified.

**Comment by maxteufel** [comment]
So we can tick that because we notified them.

**Comment by pelya** [comment]
Updated Android package: https://sourceforge.net/projects/libsdl-android/files/apk/SuperTux/

**Comment by maxteufel** [comment]
Let's finally close this, no one seems to care about notifying uptodown (whatever that is).

**Comment by tobbi** [comment]
SuperTux Portable updated:
http://portableapps.com/apps/games/supertux-portable

**Comment by tobbi** [comment]
uptodown updated:
http://supertux.uptodown.com/
