### ISSUE TITLE
SuperTux Team Meeting Jan 9 2016

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#292]
There will be a meeting 9th January 2016 15:00 UTC and we don't have any topics so far, please write there what you want to discuss about. Write it to the comment or just edit this post.

- [x] The future of the forest world (@Karkus476)
    - [x] New worldmap?
    - [x] New levels?
    - [x] New boss
    - [x] Ghost World? Transition?
- [x] SuperTux level editor (@Karkus476)
   - [x] Have a SuperTux level website and have a way to upload levels there from the editor.
- [x] Multiplayer? See #224 (@Karkus476)
- [x] More moves? (@Hume2)
    - [x] Swimming?
    - [x] Crawling?
- [x] Water physics? Melting/Burning/Freezing animations?
- [x] Scripting additions to make more interesting levels
- [x] What do interesting levels actually comprise?

When is the meeting in progress, please use the personal chat to discuss off-topic subjects, like how-to. We need to keep on topic to get things done.

**Edited by @Karkus476 7th Jan 2016: Implement @pazkero's suggestions, reword**

**Comment by Karkus476** [comment]
We can tick things off the list as we discuss them.

**Comment by Hume2** [comment]
That's a good idea.

**Comment by giby** [comment]
Forest needs just a decent boss... 
For next words, we needs new graphism...

**Comment by pazkero** [comment]
Did you meant:
"The leader of this meeting will be probably Tobbi, so do not annoy him. When is the meeting in progress, please use the personal chat to discuss off-topic subjects, like how-to. Thanks for keeping the channel for on-topic use only."

I usually, after finishing a release, encourage a "immediate next release planning" and review the last one (how could we *not* take, like, 3 years for next release?, for example)
Immediate-next-release only because usually I already have archived how I want the final product to look like, so I just need to discuss until what point of it should be done to next release. It applies mostly to **story**, and major code changes for it, but optimization, features, bugfixing and this sort of things are done during the process, and not on a meeting.


Well, this is my opinion, what I would do.
It may not work with SuperTux, but usually two topics persists:
* Learning from previous release mistakes
* What story will we add for next release, and next release only?

**Comment by maxteufel** [comment]
> [...] When is the meeting in progress, discuss ON TOPIC only! When you want to say something off-topic, use personal chat! Get rid of any off-topic notes, do not ask how to do something!

Suggestion: to ensure this, we could keep the channel `+mz` (+m: moderated: only voiced and opped users can speak; +z: relaxed moderation: ops will see messages caught by +m) and voice all users that want to say something useful.

**Comment by Hume2** [comment]
@maxteufel Good idea.

**Comment by Karkus476** [comment]
Thanks for contributing, everyone

**Comment by Hume2** [comment]
Someone just has to write the results somewhere. There's what I've noted:
* Forest
 * The transition to the ghost forest will be via a cave
 * Deciding the boss is useless at the meeting, someone has just to think it himself.
* Editor
 * The editor will be Flexlay.
 * Flexlay should be released before 0.5.0 to get some levels.
* Multiplayer : Posponed to 0.6.0, no decisions so far
* Moves
 * Swimming
  * All water will be swimmable.
  * Press down to toggle the swimming mode.
 * No crawling
 * Sliding the slopes will be implemented.
* Effects
 * Burning must emit light, but will stay as is.
 * Shattering animations should be improved, but not draw anything.
* Wiki will be moved to another source and pull-requests will be used for updating.
