### ISSUE TITLE
SuperTux Meeting: 10th September 2016

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#591]
In this meeting we will discuss:
Most importantly:

 - [ ] Anything left for 0.5.0
 - [ ] Setting up a regular meeting schedule

Also:

 - [ ] Issue #530, and its implementation
 - [ ] Issue #473, and its implementation
 - [ ] Issue #499, for a vote
 - [ ] Removing the data submodule (implications, and a vote)
 - [ ] Discuss the word "milestone" in regards to SuperTux milestone 1, milestone 2. Are we still using this? Our website uses it (see the downloads page).

Anyone feel free to edit this message, and please note anything written here may not have been written by me (@Karkus476)

Time: 15:00 UTC - 17:00 UTC

*Edit 1, @maxteufel, 2016-09-06 17:15 UTC: people who edit this should state what they edited below.*
*Edit 2, @Karkus476, 2016-09-06 22:36 UTC: add milestone discussion*
*Edit 3, @maxteufel, 2016-09-10 07:20 UTC: add time*

**Comment by Karkus476** [comment]
@SuperTux/developers Please feel free to add anything you wish to discuss at this meeting to the above issue.

**Comment by christ2go** [comment]
@Karkus476 About the "milestone" thing: It's still used ingame, see https://github.com/SuperTux/data/blob/92a3f1a7fefe9754d0cd2f3c5390b002b91ab7e9/credits.stxt#L976

**Comment by maxteufel** [comment]
@Karkus476 I thought we long decided we wouldn't use "milestones" (as in, those with numbers like 1, 2, 3, ...) anymore.

@christ2go We'll have to keep it for now due to string freeze.

**Comment by Karkus476** [comment]
@maxteufel Me too, until you made a document called "Milestone 3 Design Document", and we called 0.4 milestone 2. And we named the executable supertux2... it's all a mess.
