### ISSUE TITLE
0.5.0 RELEASE TODO LIST

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#594]
__TENTATIVE RELEASE DATE: September 25, 2016__

In this issue, I will gather tasks that need to be done before (or on the day of) the release of 0.5.0):
- ~~Include new contributors~~
- [x] Update list of translators in credits
- ~~Add people we might have forgotten during previous rounds (if there are any)~~
- [x] Update localization files from Transifex
- [x] Add "Thank you" announcement stating that localizers can take it easy now, once again tell them we'll be updating the font engine post-0.5. ;)
- [x] Update add-ons that need updating (including those with changed strings which were updated in the source files.
  - [x] Create language add-ons for all supported languages. 
- [x] Run through Coverity to make sure that intermittent changes didn't break the build
- [x] Update readme.md to reflect recent changes (if there are any)
- [x] Create release notes, update `NEWS.md` for 0.5.0
  - [x] Partially done because of the release candidates' notes
- [x] *git tag* the release as 0.5.0, create a new branch containing 0.5.0 code, main development will continue on the master branch.
- [x] Compile packages for major operating systems (Linux, Windows, Mac OS X) (@maths22)
  - [x] Will be done automagically when @maths22 fixes the tasks assigned to him
- [x] Create release announcement covering most important commits since 0.4.0 (also include release notes).
  - [x] Also partially done due to release candidate announcements
- [x] PR / Social Media coverage, including:
  - [x] Twitter (@supertux_team)
  - [x] FreeGameDev.org
  - [x] Mailing list
  - [x] Google+
  - [x] Reddit (/r/supertux, /r/TuxThePenguin, /r/linuxgaming, /r/gaming etc.)

**Comment by tobbi** [comment]
All done!
